### ISSUE TITLE
normaliz is overlinking

### ISSUE THREAD

**Issue by saraedum** [conda-forge/normaliz-feedstock#10]
see latest CI output, it should not link against e-antic's dependencies. Or rather only the ones that are used in the renfxx header.

**Comment by saraedum** [comment]
@isuruf: Do we need to fix this here or should this just go into upstream eventually?

**Comment by saraedum** [comment]
If I understand correctly, normaliz uses e-antic but it does not use arb. So we do not need to rerender here to upgrade to Arb 2.17. And consequently, we do not need to rerender gap/libgap.

**Comment by isuruf** [comment]
It does link against arb.

WARNING (normaliz,lib/libnormaliz.so.3.8.1): Needed DSO lib/libarb.so.2 found in ['arb']
WARNING (normaliz,lib/libnormaliz.so.3.8.1): .. but ['arb'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)

**Comment by saraedum** [comment]
But it is actually overlinking. I don't understand this well enough but let me just take out the overlinking instead.

**Comment by isuruf** [comment]
Because of inline functions in `e-antic`, (For eg: https://github.com/videlec/e-antic/blob/master/e-antic/poly_extra.h#L259-L273), downstream packages of `e-antic` also links to `arb`.
