### ISSUE TITLE
Parallelization problem of the Conda Normaliz distribution version 3.9.1 on MS Windows

### ISSUE THREAD

**Issue by w-bruns** [conda-forge/normaliz-feedstock#37]
I have tested the MS Windows normaliz.exe 3.9.1 in the Conda distribution. Unfortunately it suffers from the same parallelization problem as the MacOS binary 3.9.1 in the Normaliz distribution. (The MS Windows binary and the Linux binary 3.9.1 in the Normaliz distribution are not affected.)

I plan to publish 3.9.2 next week. It will have an extra computation step as a precaution against this problem that I have so far only seen in binaries computed with newer versions of clang. Of course this does not mean that the problem is caused by the compiler. Perhaps we have only been lucky so far.

On Linux I have seen it only with clang++-11. clang++-12 does not show it in GitHub workflows. clang++13 will be tested the next days.

**Comment by w-bruns** [comment]
It seems that the cause of the problem has been found. See https://github.com/Normaliz/Normaliz/issues/385.

**Comment by saraedum** [comment]
I assume that this has been fixed in the more recent releases?
