### ISSUE TITLE
Excellent performance

### ISSUE THREAD

**Issue by w-bruns** [conda-forge/normaliz-feedstock#7]
Issue: I have tested the new normaliz.exe for Windows. It is as fast as the Intel compiled version. 

<br/>
Environment (<code>conda list</code>): 
<details> 
```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by saraedum** [comment]
Thanks for the feedback :)
